### ISSUE TITLE
Error with graceful-fs

### ISSUE THREAD

**Issue by felixoi** [gpgekko/sbt-autoprefixer#2]
Getting this error since 2 days without changing anything. Opening this here because I just can't find the cause. Broken for muliply developer machines, jenkins and travis. Stacktrace is:
```
JsTaskFailure: internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/felix/Development/java/Ore/project/target/node-modules/webjars/fs-extra/lib/fs/index.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
```

**Comment by gpgekko** [comment]
Just tested and seeing this error locally too. It is probably because a newer version of one of the dependencies. Due to license limitations (or rather, [BinTray not understanding a newer version of a popular license and therefor rejecting webjars with that license](https://github.com/webjars/webjars/issues/1347)), not all of the latest versions of the dependencies are available, so some are restricted to older versions. If one of the other dependencies then updates to a newer version and that version expects a newer version of something else, things break. It's quite frustrating. The problem is figuring out which one became incompatible with the rest, since there usually aren't many helpful clues...
Sadly I'm not working on any frontend projects right now and therefor don't have much time that I can spend on this.
I did at one point contemplate pinning all dependencies to the versions they had at that time to reduce the chance of things breaking but I never got around to doing so. I'm now very much regretting I didn't do that...

**Comment by gpgekko** [comment]
Latest commit should at least make it function again for now. It's a bit of a dirty hack, basically forcing everything to the versions they were at in a random stale repo I had lying around, but at least your (and my) builds are hopefully working again. Keeping this open for now because this is not a permanent fix by any stretch of the imagination 😅
